language: ruby
rvm:
  - "2.2.0"
  - jruby
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rails db:migrate
  - bundle exec rails db:test:prepare
  - bundle exec rspec spec/
before_script:
  - RAILS_ENV=test bundle exec rails db:create
before_install:
  - rack update --system 2.0.0
  - rack --version
