language: ruby
rvm:
  - 2.3.1
  - jruby
services:
  - postgresql
script:
  - RAILS_ENV=test bundle exec rails db:create
  - RAILS_ENV=test bundle exec rails db:migrate
  - bundle exec rails db:test:prepare
  - bundle exec rspec
